In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [3]:
# 1-мерный массив случайных целых значений
arr_0 = np.random.randint(5, size=10)
arr_0

array([3, 4, 3, 1, 2, 0, 0, 2, 1, 4])

In [6]:
# np.random.randint(-10, 10, size=10)
np.random.randint(-10, 10, 10)

array([  0, -10,   8,  -7,   3,  -9,  -3,   5,   7,   3])

In [5]:
np.random.randint(-100, 100, size=(3, 5))

array([[ -91,  -82,   63,  -16,  -31],
       [  31,   69, -100,    2,   -3],
       [  53,   56,  -84,   69,   -6]])

In [9]:
# 2-мерный массив случайных значений с плавающей точкой в диапазоне от 0 до 1
np.random.random((3, 3))

array([[0.70612234, 0.35867567, 0.60023445],
       [0.55555433, 0.85992816, 0.75788554],
       [0.99258687, 0.09095701, 0.8908475 ]])

In [10]:
# массив случайных чисел с плавающей точкой
#   из нормального (гуассова) распределения
np.random.randn(3, 4)

array([[ 1.17537777, -0.52047231,  0.31055529,  1.0710397 ],
       [-0.15862671, -1.6304872 , -0.52918809,  0.37174674],
       [ 0.35426817, -0.47484544,  0.1316823 , -2.30849715]])

- Атрибуты

In [11]:
arr_0 = np.random.randint(5, size=10)
arr_0

array([1, 0, 2, 0, 1, 1, 1, 2, 3, 4])

In [12]:
# форма массива
arr_0.shape

(10,)

In [13]:
# тип данных
arr_0.dtype

dtype('int32')

In [14]:
# мерность массива
arr_0.ndim

1

In [15]:
# объем занимаемой памяти (в байтах)
arr_0.nbytes

40

- Методы

In [16]:
# конвертация типов данных
arr_0.astype("float16")

array([1., 0., 2., 0., 1., 1., 1., 2., 3., 4.], dtype=float16)

In [17]:
arr_1 = np.random.randint(100, size=(3,5))
arr_1

array([[53, 77, 76, 32, 57],
       [74,  9, 99, 21, 11],
       [23, 78, 42, 73, 78]])

In [19]:
# транспонирование
# arr_1.transpose()
arr_1.T

array([[53, 74, 23],
       [77,  9, 78],
       [76, 99, 42],
       [32, 21, 73],
       [57, 11, 78]])

- Индексация

In [20]:
arr_2 = np.random.randint(10, size=(3,4))
arr_2

array([[5, 2, 3, 4],
       [8, 1, 0, 5],
       [6, 0, 4, 9]])

In [22]:
# прямая индексация
arr_2[1]

array([8, 1, 0, 5])

In [23]:
# обратная индексация
arr_2[-1]

array([6, 0, 4, 9])

In [25]:
# синтаксис списков и кортежей
arr_2[2][3]

# синтаксис numpy
arr_2[2,3]

9

## Анализ данных по Титанику

In [1]:
import pandas as pd

In [3]:
#  загрузка данных из файла
data_0 = pd.read_csv("data/titanic.csv")
data_0.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [4]:
data_0.shape

(891, 15)

In [5]:
data_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [6]:
# удаление строк и столбцов с NaN или замена NaN
df = pd.DataFrame({
    "c0": {"r0": 100, "r1": 200, "r2": 300},
    "c1": {"r1": 400, "r2": 500},
    "c2": {"r0": 600, "r2": 700}
})
df

c0     c1     c2
r0  100    NaN  600.0
r1  200  400.0    NaN
r2  300  500.0  700.0

In [7]:
# удаление строк с пустыми значениями
df.dropna()

c0     c1     c2
r2  300  500.0  700.0

In [8]:
df.dropna(axis=1)

c0
r0  100
r1  200
r2  300

In [9]:
# замена пустых значений на другое значение
df.fillna(0)

c0     c1     c2
r0  100    0.0  600.0
r1  200  400.0    0.0
r2  300  500.0  700.0

In [10]:
# удаление строк по индексам
df.drop("r0")

c0     c1     c2
r1  200  400.0    NaN
r2  300  500.0  700.0

In [11]:
df.drop(["r0", "r2"])

c0     c1  c2
r1  200  400.0 NaN

In [12]:
# удаление столбцов по ключам
df.drop("c1", axis=1)

c0     c2
r0  100  600.0
r1  200    NaN
r2  300  700.0

- Очистка данных

In [13]:
data_0.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [16]:
# удаление ненужных столбцов
data_1 = data_0.drop(['sibsp', 'embarked', 'class', 'adult_male', 'deck',  'alive'], axis=1)
data_1.head()

survived  pclass     sex   age  parch     fare    who  embark_town  alone
0         0       3    male  22.0      0   7.2500    man  Southampton  False
1         1       1  female  38.0      0  71.2833  woman    Cherbourg  False
2         1       3  female  26.0      0   7.9250  woman  Southampton   True
3         1       1  female  35.0      0  53.1000  woman  Southampton  False
4         0       3    male  35.0      0   8.0500    man  Southampton   True

In [17]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   parch        891 non-null    int64  
 5   fare         891 non-null    float64
 6   who          891 non-null    object 
 7   embark_town  889 non-null    object 
 8   alone        891 non-null    bool   
dtypes: bool(1), float64(2), int64(3), object(3)
memory usage: 56.7+ KB


In [18]:
# удаление строк с пустыми значениями
data_1.dropna(inplace=True)
data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     712 non-null    int64  
 1   pclass       712 non-null    int64  
 2   sex          712 non-null    object 
 3   age          712 non-null    float64
 4   parch        712 non-null    int64  
 5   fare         712 non-null    float64
 6   who          712 non-null    object 
 7   embark_town  712 non-null    object 
 8   alone        712 non-null    bool   
dtypes: bool(1), float64(2), int64(3), object(3)
memory usage: 50.8+ KB


In [19]:
# проверка на дубликаты
data_1.duplicated().sum()

38

In [20]:
# удаление дубликатов
data_1.drop_duplicates(inplace=True)

In [21]:
data_1.duplicated().sum()

0

In [22]:
data_1.shape

(674, 9)

- Анализ данных

In [23]:
data_1.columns

Index(['survived', 'pclass', 'sex', 'age', 'parch', 'fare', 'who',
       'embark_town', 'alone'],
      dtype='object')

In [24]:
data_1.head()

survived  pclass     sex   age  parch     fare    who  embark_town  alone
0         0       3    male  22.0      0   7.2500    man  Southampton  False
1         1       1  female  38.0      0  71.2833  woman    Cherbourg  False
2         1       3  female  26.0      0   7.9250  woman  Southampton   True
3         1       1  female  35.0      0  53.1000  woman  Southampton  False
4         0       3    male  35.0      0   8.0500    man  Southampton   True

In [30]:
# сколько выживших в таблице
# data_1.survived.sum()
num_surv = data_1["survived"].sum()
num_surv

281

In [31]:
# процент выживаемости
num_surv / data_1.shape[0] * 100

41.69139465875371

In [32]:
# минимальный, средний и максимальный возрасты
data_1["age"].min(), data_1["age"].mean(), data_1["age"].max()

(0.42, 29.752848664688425, 80.0)

In [33]:
data_1.columns

Index(['survived', 'pclass', 'sex', 'age', 'parch', 'fare', 'who',
       'embark_town', 'alone'],
      dtype='object')

In [34]:
# значение столбца "survived" при условии "age" == 0.42
mask = data_1["age"] == 0.42
data_1.loc[mask, "survived"]

803    1
Name: survived, dtype: int64

In [35]:
data_1.loc[mask, :]

survived  pclass   sex   age  parch    fare    who embark_town  alone
803         1       3  male  0.42      1  8.5167  child   Cherbourg  False

In [38]:
# узнаем данные по детям до 1 года
mask = data_1["age"] <= 1
data_1.loc[mask, :]

survived  pclass     sex  age  parch     fare    who  embark_town  alone
0           0       3    male    1      0   7.2500    man  Southampton  False
1           1       1  female    1      0  71.2833  woman    Cherbourg  False
2           1       3  female    1      0   7.9250  woman  Southampton   True
3           1       1  female    1      0  53.1000  woman  Southampton  False
4           0       3    male    1      0   8.0500    man  Southampton   True
..        ...     ...     ...  ...    ...      ...    ...          ...    ...
883         0       2    male    1      0  10.5000    man  Southampton   True
885         0       3  female    1      5  29.1250  woman   Queenstown  False
887         1       1  female    1      0  30.0000  woman  Southampton   True
889         1       1    male    1      0  30.0000    man    Cherbourg   True
890         0       3    male    1      0   7.7500    man   Queenstown   True

[674 rows x 9 columns]

In [44]:
# узнаем данные по детям от 10 до 18 лет
mask = (data_1["age"] >= 10) & (data_1["age"] < 18)
data_1.loc[mask, :]

Empty DataFrame
Columns: [survived, pclass, sex, age, parch, fare, who, embark_town, alone]
Index: []

In [42]:
data_1.columns

Index(['survived', 'pclass', 'sex', 'age', 'parch', 'fare', 'who',
       'embark_town', 'alone'],
      dtype='object')

In [46]:
# GroupBy
data_1.groupby("survived")[['age', 'pclass']].mean()

age    pclass
survived               
0         1.0  2.478372
1         1.0  1.871886