In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [3]:
# 1-мерный массив случайных целых значений
arr_0 = np.random.randint(5, size=10)
arr_0

array([3, 4, 3, 1, 2, 0, 0, 2, 1, 4])

In [6]:
# np.random.randint(-10, 10, size=10)
np.random.randint(-10, 10, 10)

array([  0, -10,   8,  -7,   3,  -9,  -3,   5,   7,   3])

In [5]:
np.random.randint(-100, 100, size=(3, 5))

array([[ -91,  -82,   63,  -16,  -31],
       [  31,   69, -100,    2,   -3],
       [  53,   56,  -84,   69,   -6]])

In [9]:
# 2-мерный массив случайных значений с плавающей точкой в диапазоне от 0 до 1
np.random.random((3, 3))

array([[0.70612234, 0.35867567, 0.60023445],
       [0.55555433, 0.85992816, 0.75788554],
       [0.99258687, 0.09095701, 0.8908475 ]])

In [10]:
# массив случайных чисел с плавающей точкой
#   из нормального (гуассова) распределения
np.random.randn(3, 4)

array([[ 1.17537777, -0.52047231,  0.31055529,  1.0710397 ],
       [-0.15862671, -1.6304872 , -0.52918809,  0.37174674],
       [ 0.35426817, -0.47484544,  0.1316823 , -2.30849715]])

- Атрибуты

In [11]:
arr_0 = np.random.randint(5, size=10)
arr_0

array([1, 0, 2, 0, 1, 1, 1, 2, 3, 4])

In [12]:
# форма массива
arr_0.shape

(10,)

In [13]:
# тип данных
arr_0.dtype

dtype('int32')

In [14]:
# мерность массива
arr_0.ndim

1

In [15]:
# объем занимаемой памяти (в байтах)
arr_0.nbytes

40

- Методы

In [16]:
# конвертация типов данных
arr_0.astype("float16")

array([1., 0., 2., 0., 1., 1., 1., 2., 3., 4.], dtype=float16)

In [17]:
arr_1 = np.random.randint(100, size=(3,5))
arr_1

array([[53, 77, 76, 32, 57],
       [74,  9, 99, 21, 11],
       [23, 78, 42, 73, 78]])

In [19]:
# транспонирование
# arr_1.transpose()
arr_1.T

array([[53, 74, 23],
       [77,  9, 78],
       [76, 99, 42],
       [32, 21, 73],
       [57, 11, 78]])

- Индексация

In [20]:
arr_2 = np.random.randint(10, size=(3,4))
arr_2

array([[5, 2, 3, 4],
       [8, 1, 0, 5],
       [6, 0, 4, 9]])

In [22]:
# прямая индексация
arr_2[1]

array([8, 1, 0, 5])

In [23]:
# обратная индексация
arr_2[-1]

array([6, 0, 4, 9])

In [25]:
# синтаксис списков и кортежей
arr_2[2][3]

# синтаксис numpy
arr_2[2,3]

9